### ISSUE TITLE
colors remarks

### ISSUE THREAD

**Issue by talvy49** [holborn2019/stygmorgan#3]
Hi
The texts in red on a gray background lack contrast and sharpness.
similarly for the four beats of the measure

**Comment by holborn2019** [comment]
Sorry with my short english I cant understand...  all the colors on the program are assigned with the FTLK tool  "fluid" if you have installed FLTK just need to install it, is a single program that sure is on ubuntu repository... just run fluid then load the stygmorganui.fl ... and u can easy change any color you want .. just click on the program tree on the "make window" function to see the main window .. and then choose the widget you want to change color ... is really easy. After this just generate the .cxx .h on the menu ... then recompile.

You can do this on any .fl file :-)

Greetings
Josep

**Comment by talvy49** [comment]
HI
sorry, i'm french and my english is far from correct. I often use the google translator which is also not always correct.
In any case, thank you for the explanations

talvy
